midwest <- as.data.frame(ggplot2::midwest)
head(midwest)
tail(midwest)
View(midwest)
dim(midwest)
str(midwest)
summary(midwest)

library(dplyr)
midwset <- rename(midwest, total = poptotal)
midwest <- rename(midwest, asian = popasian)
